
package org.oasis_open.docs.ns.cmis.ws._200908;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-13T13:40:11.552+02:00
 * Generated source version: 3.2.4
 *
 */
public final class ACLServicePort_ACLServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://docs.oasis-open.org/ns/cmis/ws/200908/", "ACLService");

    private ACLServicePort_ACLServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ACLService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ACLService ss = new ACLService(wsdlURL, SERVICE_NAME);
        ACLServicePort port = ss.getACLServicePort();

        {
        System.out.println("Invoking getACL...");
        java.lang.String _getACL_repositoryId = "";
        java.lang.String _getACL_objectId = "";
        java.lang.Boolean _getACL_onlyBasicPermissions = null;
        org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType _getACL_extension = null;
        try {
            org.oasis_open.docs.ns.cmis.messaging._200908.CmisACLType _getACL__return = port.getACL(_getACL_repositoryId, _getACL_objectId, _getACL_onlyBasicPermissions, _getACL_extension);
            System.out.println("getACL.result=" + _getACL__return);

        } catch (CmisException e) {
            System.out.println("Expected exception: cmisException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking applyACL...");
        java.lang.String _applyACL_repositoryId = "";
        java.lang.String _applyACL_objectId = "";
        org.oasis_open.docs.ns.cmis.core._200908.CmisAccessControlListType _applyACL_addACEs = null;
        org.oasis_open.docs.ns.cmis.core._200908.CmisAccessControlListType _applyACL_removeACEs = null;
        org.oasis_open.docs.ns.cmis.core._200908.EnumACLPropagation _applyACL_aclPropagation = null;
        org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType _applyACL_extension = null;
        try {
            org.oasis_open.docs.ns.cmis.messaging._200908.CmisACLType _applyACL__return = port.applyACL(_applyACL_repositoryId, _applyACL_objectId, _applyACL_addACEs, _applyACL_removeACEs, _applyACL_aclPropagation, _applyACL_extension);
            System.out.println("applyACL.result=" + _applyACL__return);

        } catch (CmisException e) {
            System.out.println("Expected exception: cmisException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
