
package org.oasis_open.docs.ns.cmis.ws._200908;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-13T13:40:11.647+02:00
 * Generated source version: 3.2.4
 */

@WebFault(name = "cmisFault", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
public class CmisException extends Exception {

    private org.oasis_open.docs.ns.cmis.messaging._200908.CmisFaultType cmisFault;

    public CmisException() {
        super();
    }

    public CmisException(String message) {
        super(message);
    }

    public CmisException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public CmisException(String message, org.oasis_open.docs.ns.cmis.messaging._200908.CmisFaultType cmisFault) {
        super(message);
        this.cmisFault = cmisFault;
    }

    public CmisException(String message, org.oasis_open.docs.ns.cmis.messaging._200908.CmisFaultType cmisFault, java.lang.Throwable cause) {
        super(message, cause);
        this.cmisFault = cmisFault;
    }

    public org.oasis_open.docs.ns.cmis.messaging._200908.CmisFaultType getFaultInfo() {
        return this.cmisFault;
    }
}
