
package org.oasis_open.docs.ns.cmis.ws._200908;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-13T13:40:11.496+02:00
 * Generated source version: 3.2.4
 *
 */
public final class DiscoveryServicePort_DiscoveryServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://docs.oasis-open.org/ns/cmis/ws/200908/", "DiscoveryService");

    private DiscoveryServicePort_DiscoveryServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DiscoveryService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        DiscoveryService ss = new DiscoveryService(wsdlURL, SERVICE_NAME);
        DiscoveryServicePort port = ss.getDiscoveryServicePort();

        {
        System.out.println("Invoking query...");
        org.oasis_open.docs.ns.cmis.messaging._200908.Query _query_parameters = null;
        try {
            org.oasis_open.docs.ns.cmis.messaging._200908.QueryResponse _query__return = port.query(_query_parameters);
            System.out.println("query.result=" + _query__return);

        } catch (CmisException e) {
            System.out.println("Expected exception: cmisException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getContentChanges...");
        java.lang.String _getContentChanges_repositoryId = "";
        java.lang.String _getContentChanges_changeLogTokenVal = "";
        javax.xml.ws.Holder<java.lang.String> _getContentChanges_changeLogToken = new javax.xml.ws.Holder<java.lang.String>(_getContentChanges_changeLogTokenVal);
        java.lang.Boolean _getContentChanges_includeProperties = null;
        java.lang.String _getContentChanges_filter = "";
        java.lang.Boolean _getContentChanges_includePolicyIds = null;
        java.lang.Boolean _getContentChanges_includeACL = null;
        java.math.BigInteger _getContentChanges_maxItems = new java.math.BigInteger("0");
        org.oasis_open.docs.ns.cmis.messaging._200908.CmisExtensionType _getContentChanges_extension = null;
        javax.xml.ws.Holder<org.oasis_open.docs.ns.cmis.messaging._200908.CmisObjectListType> _getContentChanges_objects = new javax.xml.ws.Holder<org.oasis_open.docs.ns.cmis.messaging._200908.CmisObjectListType>();
        try {
            port.getContentChanges(_getContentChanges_repositoryId, _getContentChanges_changeLogToken, _getContentChanges_includeProperties, _getContentChanges_filter, _getContentChanges_includePolicyIds, _getContentChanges_includeACL, _getContentChanges_maxItems, _getContentChanges_extension, _getContentChanges_objects);

            System.out.println("getContentChanges._getContentChanges_changeLogToken=" + _getContentChanges_changeLogToken.value);
            System.out.println("getContentChanges._getContentChanges_objects=" + _getContentChanges_objects.value);
        } catch (CmisException e) {
            System.out.println("Expected exception: cmisException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
