package org.oasis_open.docs.ns.cmis.ws._200908;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-13T13:40:11.695+02:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "PolicyService",
                  wsdlLocation = "file:alfresco.wsdl",
                  targetNamespace = "http://docs.oasis-open.org/ns/cmis/ws/200908/")
public class PolicyService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://docs.oasis-open.org/ns/cmis/ws/200908/", "PolicyService");
    public final static QName PolicyServicePort = new QName("http://docs.oasis-open.org/ns/cmis/ws/200908/", "PolicyServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:alfresco.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PolicyService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:alfresco.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PolicyService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PolicyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PolicyService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PolicyService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PolicyService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PolicyService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PolicyServicePort
     */
    @WebEndpoint(name = "PolicyServicePort")
    public PolicyServicePort getPolicyServicePort() {
        return super.getPort(PolicyServicePort, PolicyServicePort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PolicyServicePort
     */
    @WebEndpoint(name = "PolicyServicePort")
    public PolicyServicePort getPolicyServicePort(WebServiceFeature... features) {
        return super.getPort(PolicyServicePort, PolicyServicePort.class, features);
    }

}
