package org.oasis_open.docs.ns.cmis.ws._200908;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-13T13:40:11.703+02:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "RelationshipService",
                  wsdlLocation = "file:alfresco.wsdl",
                  targetNamespace = "http://docs.oasis-open.org/ns/cmis/ws/200908/")
public class RelationshipService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://docs.oasis-open.org/ns/cmis/ws/200908/", "RelationshipService");
    public final static QName RelationshipServicePort = new QName("http://docs.oasis-open.org/ns/cmis/ws/200908/", "RelationshipServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:alfresco.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RelationshipService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:alfresco.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RelationshipService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RelationshipService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RelationshipService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RelationshipService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RelationshipService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RelationshipService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns RelationshipServicePort
     */
    @WebEndpoint(name = "RelationshipServicePort")
    public RelationshipServicePort getRelationshipServicePort() {
        return super.getPort(RelationshipServicePort, RelationshipServicePort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RelationshipServicePort
     */
    @WebEndpoint(name = "RelationshipServicePort")
    public RelationshipServicePort getRelationshipServicePort(WebServiceFeature... features) {
        return super.getPort(RelationshipServicePort, RelationshipServicePort.class, features);
    }

}
